# Window Detection and Permutation ANOVA

## For Best Frans

In [3]:
from analyses.response_window_analysis import run_permutation_anova_by_window
from analyses.spike_count import extract_spike_counts_from_windows
import pandas as pd
from analyses.response_window_finder.threshold_window_detection import compute_timebinned_spikecount_per_neuron, \
    z_score, threshold_and_fill_gap, extract_consecutive_ranges, remove_consecutive_tuples, \
    find_corresponding_values_for_index_ranges
from tqdm import tqdm
import numpy as np
from analyses.data_readers.recording_metadata_reader import RecordingMetadataReader

In [1]:
# Detect windows for best frans
prelim = RecordingMetadataReader().get_metadata_for_preliminary_analysis()
results = []
bin_size = 0.05  # in sec
rounded_time = np.round(np.arange(bin_size, 3.50, bin_size), 2)
monkey_group = 'Best Frans'
for _, row in tqdm(prelim.iterrows(), total = len(prelim), desc = "Processing each recording day..."):
    round_no = row['Round No.']
    date = str(row['Date'].strftime('%Y-%m-%d'))
    timebin_spikecount_list = compute_timebinned_spikecount_per_neuron(date, round_no, bin_size, monkey_group)
    for _, r in timebin_spikecount_list.iterrows():
        data = r['TotalSpikeCountList']
        neuron = r['NeuronID']
        normalized_data = z_score(data)
        thresh = 0.5
        change_points = threshold_and_fill_gap(normalized_data, thresh)
        windows = extract_consecutive_ranges(change_points)
        filtered_windows = remove_consecutive_tuples(windows)
        time_windows = find_corresponding_values_for_index_ranges(filtered_windows, rounded_time)
        if len(time_windows) > 0:
            for start_time, end_time in time_windows:
                results.append({
                    'NeuronID': neuron,
                    'WindowStart_ms': int(start_time * 1000),
                    'WindowEnd_ms': int(end_time * 1000)
                })

NameError: name 'RecordingMetadataReader' is not defined

In [3]:
# Detected windows
bf_results_df = pd.DataFrame(results)
bf_results_df = bf_results_df.sort_values(by=['NeuronID'])
bf_results_df

                              NeuronID  WindowStart_ms  WindowEnd_ms
0    2023-09-26_1_Channel.C_005_Unit 1            1700          1850
1    2023-09-26_1_Channel.C_009_Unit 1             450           550
2    2023-09-26_1_Channel.C_009_Unit 1            2000          2150
3    2023-09-26_1_Channel.C_011_Unit 2            1000          1100
4    2023-09-26_1_Channel.C_011_Unit 2            1450          1650
..                                 ...             ...           ...
813  2023-12-18_3_Channel.C_015_Unit 1             400           500
814  2023-12-18_3_Channel.C_015_Unit 1             850          1050
816  2023-12-18_3_Channel.C_020_Unit 1             200           500
817  2023-12-18_3_Channel.C_026_Unit 1             300           500
818  2023-12-18_3_Channel.C_029_Unit 1              50           300

[819 rows x 3 columns]

In [9]:
# Extract spike counts in the windows
bf_final_df = extract_spike_counts_from_windows(bf_results_df)

Extracting spike counts: 100%|██████████| 819/819 [00:53<00:00, 15.30it/s]

In [17]:
# Run Perm ANOVA on BestFrans
bestfrans_df = bf_final_df[bf_final_df['MonkeyGroup'] == 'Best Frans']
bf_perm_results, bf_sig_results = run_permutation_anova_by_window(bestfrans_df,
                                category_col='MonkeyName',
                                neuron_col='NeuronID',
                                count_col='SpikeCount',
                                window_start_col='WindowStart_ms',
                                window_end_col='WindowEnd_ms',
                                n_permutations=1000,
                                alpha=0.05,
                                plot=False)

Running Perm ANOVA per (Neuron, Window): 100%|██████████| 819/819 [01:15<00:00, 10.91it/s]

All Results:
                              NeuronID  WindowStart_ms  WindowEnd_ms  \
0    2023-09-26_1_Channel.C_005_Unit 1            1700          1850
1    2023-09-26_1_Channel.C_009_Unit 1             450           550
2    2023-09-26_1_Channel.C_009_Unit 1            2000          2150
3    2023-09-26_1_Channel.C_011_Unit 2            1000          1100
4    2023-09-26_1_Channel.C_011_Unit 2            1450          1650
..                                 ...             ...           ...
814  2023-12-18_3_Channel.C_015_Unit 1             850          1050
815  2023-12-18_3_Channel.C_015_Unit 1            1150          1250
816  2023-12-18_3_Channel.C_020_Unit 1             200           500
817  2023-12-18_3_Channel.C_026_Unit 1             300           500
818  2023-12-18_3_Channel.C_029_Unit 1              50           300

     F-statistic  p-value
0       0.592963    0.686
1       0.605478    0.607
2       1.621436    0.139
3       0.723356    0.904
4       0.585557    0.713
..           ...      ...
814     0.468750    0.769
815     1.730769    0.180
816     5.792553    0.003
817     0.509852    0.744
818     0.746637    0.610

[819 rows x 5 columns]

Significant windows (p < 0.05):
                              NeuronID  WindowStart_ms  WindowEnd_ms  \
47   2023-09-26_3_Channel.C_027_Unit 1             250           450
89   2023-09-29_3_Channel.C_029_Unit 1             400           550
119  2023-10-03_3_Channel.C_013_Unit 1             750           850
134  2023-10-03_4_Channel.C_010_Unit 1             100           650
148  2023-10-03_4_Channel.C_025_Unit 2             850           950
166         2023-10-04_1_Channel.C_024             300           500
171  2023-10-04_2_Channel.C_009_Unit 1             200           400
174  2023-10-04_2_Channel.C_009_Unit 2            1300          1500
191  2023-10-04_3_Channel.C_009_Unit 1             150           350
299         2023-10-09_3_Channel.C_024             700           950
308         2023-10-10_2_Channel.C_010             300           600
318         2023-10-10_2_Channel.C_022            1500          1600
330         2023-10-10_3_Channel.C_022            1250          1350
375         2023-10-11_3_Channel.C_024            1100          1200
398         2023-10-27_3_Channel.C_015             350           450
399         2023-10-27_3_Channel.C_015             850          1000
443         2023-11-20_2_Channel.C_009            1950          2050
472         2023-11-22_2_Channel.C_009             250           450
498         2023-11-22_3_Channel.C_027             250           450
502         2023-11-22_3_Channel.C_028            1100          1200
503         2023-11-22_3_Channel.C_028            1850          1950
530         2023-11-25_1_Channel.C_009              50           250
538         2023-11-25_1_Channel.C_017             300           400
560         2023-11-25_2_Channel.C_016             750           850
581         2023-11-25_3_Channel.C_018            1350          1450
606         2023-11-27_3_Channel.C_002             200           350
612         2023-11-27_3_Channel.C_017             200           600
620         2023-11-28_3_Channel.C_009             600           750
645         2023-11-28_4_Channel.C_015            1450          1550
683         2023-12-07_1_Channel.C_008             650           800
745         2023-12-11_4_Channel.C_015            1350          1450
764         2023-12-14_1_Channel.C_026            1650          1800
775         2023-12-14_4_Channel.C_006              50           650
797  2023-12-18_2_Channel.C_012_Unit 1             300           400
799  2023-12-18_2_Channel.C_012_Unit 1            1850          2050
800  2023-12-18_2_Channel.C_012_Unit 2             150           300
801  2023-12-18_2_Channel.C_012_Unit 2            1300          1400
803  2023-12-18_2_Channel.C_013_Unit 1            2100          2200
807  2023-12-18_2_Channel.C_017_Unit 2             200           300
813  2023-12-18_3_Channel.C_015_Unit 1             400           500
816  2023-12-18_3_Channel.C_020_Unit 1             200           500

     F-statistic  p-value
47      3.282644    0.015
89      3.152212    0.026
119     2.557818    0.039
134     2.706827    0.035
148     3.512962    0.004
166     1.949858    0.041
171     2.686364    0.031
174     2.858108    0.015
191     5.344846    0.000
299     2.169755    0.002
308     2.597494    0.042
318     2.690596    0.046
330     2.397490    0.042
375     2.423101    0.047
398     3.439655    0.022
399     3.156132    0.022
443     2.690856    0.042
472     4.893498    0.003
498     2.659091    0.043
502     2.686667    0.044
503     3.598675    0.005
530     2.280603    0.047
538     2.755981    0.044
560     2.866242    0.004
581     2.707548    0.040
606     3.891225    0.004
612     3.456716    0.017
620     2.762926    0.045
645     2.487624    0.047
683     2.510015    0.045
745     3.102865    0.030
764     2.438914    0.039
775     3.169577    0.020
797     2.607143    0.042
799     3.582969    0.009
800     2.723684    0.044
801     2.550000    0.037
803     3.095638    0.026
807     4.800000    0.003
813     3.082677    0.026
816     5.792553    0.003

In [18]:
bf_sig_results.head()

,NeuronID,WindowStart_ms,WindowEnd_ms,F-statistic,p-value
47,2023-09-26_3_Channel.C_027_Unit 1,250,450,3.282644,0.015
89,2023-09-29_3_Channel.C_029_Unit 1,400,550,3.152212,0.026
119,2023-10-03_3_Channel.C_013_Unit 1,750,850,2.557818,0.039
134,2023-10-03_4_Channel.C_010_Unit 1,100,650,2.706827,0.035
148,2023-10-03_4_Channel.C_025_Unit 2,850,950,3.512962,0.004

In [ ]:
bf_sig_results[['Date', 'Round No.', 'Cell']] = bf_sig_results['NeuronID'].str.split('_', n=2, expand=True)
bf_sig_results['Time Window'] = list(zip(bf_sig_results['WindowStart_ms'], bf_sig_results['WindowEnd_ms']))
bf_sig_results.head() # --- save this and share with Ed !!

In [31]:
# Get spike counts anova passed windows
bf_spike_count_for_sig_windows_anova_passed = extract_spike_counts_from_windows(bf_sig_results)

Extracting spike counts: 100%|██████████| 41/41 [00:28<00:00,  1.45it/s]

In [35]:
bf_spike_count = bf_spike_count_for_sig_windows_anova_passed.copy()
bf_spike_count.head()

,NeuronID,MonkeyName,MonkeyGroup,TaskField,WindowStart_ms,WindowEnd_ms,SpikeCount
0,2023-09-26_3_Channel.C_027_Unit 1,40J,Stranger Things,1695753698845000,250,450,0
1,2023-09-26_3_Channel.C_027_Unit 1,68F,Best Frans,1695753698942000,250,450,3
2,2023-09-26_3_Channel.C_027_Unit 1,68Y,Stranger Things,1695753698996000,250,450,0
3,2023-09-26_3_Channel.C_027_Unit 1,35Y,Instigators,1695753699056000,250,450,3
4,2023-09-26_3_Channel.C_027_Unit 1,DF2I,Stranger Things,1695753699165000,250,450,0

In [41]:
bf_spike_count[['Date', 'Round No.', 'Cell']] = bf_spike_count['NeuronID'].str.split('_', n=2, expand=True)
bf_spike_count['Time Window'] = list(zip(bf_spike_count['WindowStart_ms'], bf_spike_count['WindowEnd_ms']))
bf_spike_count.head()

,NeuronID,MonkeyName,MonkeyGroup,TaskField,WindowStart_ms,WindowEnd_ms,SpikeCount,Date,Round No.,Cell,Time Window
0,2023-09-26_3_Channel.C_027_Unit 1,40J,Stranger Things,1695753698845000,250,450,0,2023-09-26,3,Channel.C_027_Unit 1,"(250, 450)"
1,2023-09-26_3_Channel.C_027_Unit 1,68F,Best Frans,1695753698942000,250,450,3,2023-09-26,3,Channel.C_027_Unit 1,"(250, 450)"
2,2023-09-26_3_Channel.C_027_Unit 1,68Y,Stranger Things,1695753698996000,250,450,0,2023-09-26,3,Channel.C_027_Unit 1,"(250, 450)"
3,2023-09-26_3_Channel.C_027_Unit 1,35Y,Instigators,1695753699056000,250,450,3,2023-09-26,3,Channel.C_027_Unit 1,"(250, 450)"
4,2023-09-26_3_Channel.C_027_Unit 1,DF2I,Stranger Things,1695753699165000,250,450,0,2023-09-26,3,Channel.C_027_Unit 1,"(250, 450)"

In [44]:
group_cols = ['Date', 'Round No.', 'Cell', 'Time Window','MonkeyName']
bf_spike_count['Date'] = bf_spike_count['Date'].astype(str)
bf_grouped_df = bf_spike_count.groupby(group_cols)['SpikeCount'].apply(list).reset_index()
bf_final_spike_count_df = bf_grouped_df.pivot(
    index=['Date', 'Round No.', 'Cell', 'Time Window'],
    columns='MonkeyName',
    values='SpikeCount'
).reset_index()
print(bf_final_spike_count_df.head()) # -- save this and share with Ed!!

### For Zombies

In [4]:
# Detect windows for zombies
prelim = RecordingMetadataReader().get_metadata_for_preliminary_analysis()
results = []
bin_size = 0.05  # in sec
rounded_time = np.round(np.arange(bin_size, 3.50, bin_size), 2)
monkey_group = 'Zombies'
for _, row in tqdm(prelim.iterrows(), total = len(prelim), desc = "Processing each recording day..."):
    round_no = row['Round No.']
    date = str(row['Date'].strftime('%Y-%m-%d'))
    timebin_spikecount_list = compute_timebinned_spikecount_per_neuron(date, round_no, bin_size, monkey_group)
    for _, r in timebin_spikecount_list.iterrows():
        data = r['TotalSpikeCountList']
        neuron = r['NeuronID']
        normalized_data = z_score(data)
        thresh = 0.5
        change_points = threshold_and_fill_gap(normalized_data, thresh)
        windows = extract_consecutive_ranges(change_points)
        filtered_windows = remove_consecutive_tuples(windows)
        time_windows = find_corresponding_values_for_index_ranges(filtered_windows, rounded_time)
        if len(time_windows) > 0:
            for start_time, end_time in time_windows:
                results.append({
                    'NeuronID': neuron,
                    'WindowStart_ms': int(start_time * 1000),
                    'WindowEnd_ms': int(end_time * 1000)
                })

Processing each recording day...: 100%|██████████| 54/54 [02:31<00:00,  2.81s/it]

In [5]:
# Detected windows
zombies_results_df = pd.DataFrame(results)
zombies_results_df = zombies_results_df.sort_values(by=['NeuronID'])
zombies_results_df.head()

                            NeuronID  WindowStart_ms  WindowEnd_ms
0  2023-09-26_1_Channel.C_005_Unit 1             300           400
1  2023-09-26_1_Channel.C_005_Unit 1             700           900
2  2023-09-26_1_Channel.C_011_Unit 1             350           500
3  2023-09-26_1_Channel.C_012_Unit 3             350           650
4  2023-09-26_1_Channel.C_012_Unit 3             750           850

In [6]:
# Extract spike counts in the windows
zombies_extracted_spikes_df = extract_spike_counts_from_windows(zombies_results_df)

Extracting spike counts: 100%|██████████| 952/952 [00:54<00:00, 17.44it/s]

In [7]:
# Run Perm ANOVA on BestFrans
zombies_df = zombies_extracted_spikes_df[zombies_extracted_spikes_df['MonkeyGroup'] == monkey_group]
_, zom_sig_results = run_permutation_anova_by_window(zombies_df,
                                category_col='MonkeyName',
                                neuron_col='NeuronID',
                                count_col='SpikeCount',
                                window_start_col='WindowStart_ms',
                                window_end_col='WindowEnd_ms',
                                n_permutations=1000,
                                alpha=0.05,
                                plot=False)

Running Perm ANOVA per (Neuron, Window): 100%|██████████| 952/952 [01:58<00:00,  8.01it/s]

All Results:
                              NeuronID  WindowStart_ms  WindowEnd_ms  \
0    2023-09-26_1_Channel.C_005_Unit 1             300           400
1    2023-09-26_1_Channel.C_005_Unit 1             700           900
2    2023-09-26_1_Channel.C_011_Unit 1             350           500
3    2023-09-26_1_Channel.C_012_Unit 3             350           650
4    2023-09-26_1_Channel.C_012_Unit 3             750           850
..                                 ...             ...           ...
947  2023-12-18_3_Channel.C_021_Unit 1             600           800
948  2023-12-18_3_Channel.C_021_Unit 1            1000          1300
949  2023-12-18_3_Channel.C_026_Unit 1             100           200
950  2023-12-18_3_Channel.C_026_Unit 1             500           600
951  2023-12-18_3_Channel.C_029_Unit 1              50           350

     F-statistic  p-value
0       0.815823    0.445
1       1.006339    0.447
2       1.029580    0.409
3       0.782943    0.672
4       0.796947    0.553
..           ...      ...
947     1.065941    0.379
948     1.104037    0.350
949     0.337500    0.981
950     1.125000    0.463
951     0.819838    0.588

[952 rows x 5 columns]

Significant windows (p < 0.05):
                              NeuronID  WindowStart_ms  WindowEnd_ms  \
27   2023-09-26_2_Channel.C_011_Unit 1             700          1000
28          2023-09-26_2_Channel.C_020              50           150
40   2023-09-26_3_Channel.C_007_Unit 2             100           200
132  2023-10-03_3_Channel.C_006_Unit 1             200           400
134  2023-10-03_3_Channel.C_006_Unit 1            2150          2250
159  2023-10-03_3_Channel.C_026_Unit 1            1900          2000
163         2023-10-03_4_Channel.C_006             450           650
167  2023-10-03_4_Channel.C_010_Unit 2             200           650
187         2023-10-03_4_Channel.C_026            1000          1100
191  2023-10-04_1_Channel.C_004_Unit 1             150           400
202  2023-10-04_1_Channel.C_019_Unit 3             150           400
219  2023-10-04_2_Channel.C_018_Unit 1             150           500
225  2023-10-04_3_Channel.C_002_Unit 1             150           400
227  2023-10-04_3_Channel.C_004_Unit 2             100           500
228  2023-10-04_3_Channel.C_009_Unit 1             150           500
231  2023-10-04_3_Channel.C_009_Unit 3             100           450
275  2023-10-04_4_Channel.C_022_Unit 2             150           650
287  2023-10-04_4_Channel.C_027_Unit 1             350           650
293  2023-10-05_1_Channel.C_004_Unit 1            1000          1100
312  2023-10-05_2_Channel.C_009_Unit 1             500           850
316  2023-10-05_2_Channel.C_018_Unit 1              50           350
325  2023-10-05_2_Channel.C_019_Unit 2            2200          2300
341         2023-10-09_3_Channel.C_013             600           750
354         2023-10-10_2_Channel.C_007            1150          1250
361         2023-10-10_2_Channel.C_011             400           600
368         2023-10-10_2_Channel.C_021             300           550
370         2023-10-10_2_Channel.C_021            1550          1650
400         2023-10-11_1_Channel.C_014             200           400
449         2023-10-11_3_Channel.C_013            1650          1800
479         2023-10-27_3_Channel.C_007            1750          1900
481         2023-10-27_3_Channel.C_013            1600          1900
512         2023-10-27_4_Channel.C_011             200           700
518         2023-10-27_4_Channel.C_020             200           650
527         2023-11-20_1_Channel.C_013             850           950
540         2023-11-20_2_Channel.C_006            2200          2300
638         2023-11-25_1_Channel.C_014            1500          1600
642         2023-11-25_1_Channel.C_019             100           500
676         2023-11-25_3_Channel.C_018              50           150
724         2023-11-28_3_Channel.C_007             700           850
745         2023-11-28_4_Channel.C_015             350           500
771         2023-12-05_4_Channel.C_015             650           750
791         2023-12-07_2_Channel.C_003             300           650
802         2023-12-07_2_Channel.C_022             500           700
865         2023-12-14_1_Channel.C_008             900          1050
873         2023-12-14_1_Channel.C_024            1450          1750
904         2023-12-14_4_Channel.C_006            1900          2000
907         2023-12-14_4_Channel.C_008             750           850
917  2023-12-18_1_Channel.C_008_Unit 2            1900          2000
931  2023-12-18_2_Channel.C_012_Unit 2             200           350
945  2023-12-18_3_Channel.C_015_Unit 1            2000          2150
946  2023-12-18_3_Channel.C_020_Unit 1             150           400

     F-statistic  p-value
27      2.408329    0.024
28      3.053653    0.005
40      2.260290    0.041
132     4.400109    0.000
134     4.370457    0.000
159     3.619540    0.001
163     2.890313    0.006
167     3.515444    0.000
187     2.084164    0.044
191     6.857850    0.000
202     4.967133    0.000
219    12.549542    0.000
225     5.019932    0.001
227     2.210789    0.037
228     3.696778    0.000
231     2.161511    0.038
275     3.480455    0.002
287     4.469791    0.001
293     2.125585    0.042
312     3.726000    0.002
316     2.579143    0.011
325     2.134615    0.038
341     2.493377    0.016
354     2.276471    0.030
361     2.430960    0.011
368     2.702228    0.006
370     2.129132    0.039
400     2.034085    0.045
449     3.026091    0.002
479     2.533262    0.015
481     2.059445    0.043
512     2.948020    0.013
518     2.888715    0.010
527     2.230932    0.038
540     3.046154    0.008
638     2.549832    0.014
642     2.264352    0.028
676     2.268348    0.038
724     2.478462    0.019
745     2.219731    0.039
771     2.129610    0.043
791     1.346868    0.047
802     1.966875    0.035
865     2.170377    0.027
873     5.250529    0.000
904     2.573589    0.013
907     2.127436    0.035
917     1.933099    0.034
931     2.174497    0.030
945     2.180261    0.036
946     2.706683    0.008

In [11]:
zom_sig_results.head()

,NeuronID,WindowStart_ms,WindowEnd_ms,F-statistic,p-value,Date,Round No.,Cell,Time Window
27,2023-09-26_2_Channel.C_011_Unit 1,700,1000,2.408329,0.024,2023-09-26,2,Channel.C_011_Unit 1,"(700, 1000)"
28,2023-09-26_2_Channel.C_020,50,150,3.053653,0.005,2023-09-26,2,Channel.C_020,"(50, 150)"
40,2023-09-26_3_Channel.C_007_Unit 2,100,200,2.260290,0.041,2023-09-26,3,Channel.C_007_Unit 2,"(100, 200)"
132,2023-10-03_3_Channel.C_006_Unit 1,200,400,4.400109,0.000,2023-10-03,3,Channel.C_006_Unit 1,"(200, 400)"
134,2023-10-03_3_Channel.C_006_Unit 1,2150,2250,4.370457,0.000,2023-10-03,3,Channel.C_006_Unit 1,"(2150, 2250)"

In [12]:
zom_sig_copy= zom_sig_results.copy()
zom_sig_copy[['Date', 'Round No.', 'Cell']] = zom_sig_results['NeuronID'].str.split('_', n=2, expand=True)
zom_sig_copy['Time Window'] = list(zip(zom_sig_copy['WindowStart_ms'], zom_sig_copy['WindowEnd_ms']))
zom_sig_copy.head() # --- save this and share with Ed !!

,NeuronID,WindowStart_ms,WindowEnd_ms,F-statistic,p-value,Date,Round No.,Cell,Time Window
27,2023-09-26_2_Channel.C_011_Unit 1,700,1000,2.408329,0.024,2023-09-26,2,Channel.C_011_Unit 1,"(700, 1000)"
28,2023-09-26_2_Channel.C_020,50,150,3.053653,0.005,2023-09-26,2,Channel.C_020,"(50, 150)"
40,2023-09-26_3_Channel.C_007_Unit 2,100,200,2.260290,0.041,2023-09-26,3,Channel.C_007_Unit 2,"(100, 200)"
132,2023-10-03_3_Channel.C_006_Unit 1,200,400,4.400109,0.000,2023-10-03,3,Channel.C_006_Unit 1,"(200, 400)"
134,2023-10-03_3_Channel.C_006_Unit 1,2150,2250,4.370457,0.000,2023-10-03,3,Channel.C_006_Unit 1,"(2150, 2250)"

In [10]:
zom_sig_copy

,NeuronID,WindowStart_ms,WindowEnd_ms,F-statistic,p-value,Date,Round No.,Cell,Time Window
27,2023-09-26_2_Channel.C_011_Unit 1,700,1000,2.408329,0.024,2023-09-26,2,Channel.C_011_Unit 1,"(700, 1000)"
28,2023-09-26_2_Channel.C_020,50,150,3.053653,0.005,2023-09-26,2,Channel.C_020,"(50, 150)"
40,2023-09-26_3_Channel.C_007_Unit 2,100,200,2.260290,0.041,2023-09-26,3,Channel.C_007_Unit 2,"(100, 200)"
132,2023-10-03_3_Channel.C_006_Unit 1,200,400,4.400109,0.000,2023-10-03,3,Channel.C_006_Unit 1,"(200, 400)"
134,2023-10-03_3_Channel.C_006_Unit 1,2150,2250,4.370457,0.000,2023-10-03,3,Channel.C_006_Unit 1,"(2150, 2250)"
159,2023-10-03_3_Channel.C_026_Unit 1,1900,2000,3.619540,0.001,2023-10-03,3,Channel.C_026_Unit 1,"(1900, 2000)"
163,2023-10-03_4_Channel.C_006,450,650,2.890313,0.006,2023-10-03,4,Channel.C_006,"(450, 650)"
167,2023-10-03_4_Channel.C_010_Unit 2,200,650,3.515444,0.000,2023-10-03,4,Channel.C_010_Unit 2,"(200, 650)"
187,2023-10-03_4_Channel.C_026,1000,1100,2.084164,0.044,2023-10-03,4,Channel.C_026,"(1000, 1100)"
191,2023-10-04_1_Channel.C_004_Unit 1,150,400,6.857850,0.000,2023-10-04,1,Channel.C_004_Unit 1,"(150, 400)"
202,2023-10-04_1_Channel.C_019_Unit 3,150,400,4.967133,0.000,2023-10-04,1,Channel.C_019_Unit 3,"(150, 400)"
219,2023-10-04_2_Channel.C_018_Unit 1,150,500,12.549542,0.000,2023-10-04,2,Channel.C_018_Unit 1,"(150, 500)"
225,2023-10-04_3_Channel.C_002_Unit 1,150,400,5.019932,0.001,2023-10-04,3,Channel.C_002_Unit 1,"(150, 400)"
227,2023-10-04_3_Channel.C_004_Unit 2,100,500,2.210789,0.037,2023-10-04,3,Channel.C_004_Unit 2,"(100, 500)"
228,2023-10-04_3_Channel.C_009_Unit 1,150,500,3.696778,0.000,2023-10-04,3,Channel.C_009_Unit 1,"(150, 500)"
231,2023-10-04_3_Channel.C_009_Unit 3,100,450,2.161511,0.038,2023-10-04,3,Channel.C_009_Unit 3,"(100, 450)"
275,2023-10-04_4_Channel.C_022_Unit 2,150,650,3.480455,0.002,2023-10-04,4,Channel.C_022_Unit 2,"(150, 650)"
287,2023-10-04_4_Channel.C_027_Unit 1,350,650,4.469791,0.001,2023-10-04,4,Channel.C_027_Unit 1,"(350, 650)"
293,2023-10-05_1_Channel.C_004_Unit 1,1000,1100,2.125585,0.042,2023-10-05,1,Channel.C_004_Unit 1,"(1000, 1100)"
312,2023-10-05_2_Channel.C_009_Unit 1,500,850,3.726000,0.002,2023-10-05,2,Channel.C_009_Unit 1,"(500, 850)"
316,2023-10-05_2_Channel.C_018_Unit 1,50,350,2.579143,0.011,2023-10-05,2,Channel.C_018_Unit 1,"(50, 350)"
325,2023-10-05_2_Channel.C_019_Unit 2,2200,2300,2.134615,0.038,2023-10-05,2,Channel.C_019_Unit 2,"(2200, 2300)"
341,2023-10-09_3_Channel.C_013,600,750,2.493377,0.016,2023-10-09,3,Channel.C_013,"(600, 750)"
354,2023-10-10_2_Channel.C_007,1150,1250,2.276471,0.030,2023-10-10,2,Channel.C_007,"(1150, 1250)"
361,2023-10-10_2_Channel.C_011,400,600,2.430960,0.011,2023-10-10,2,Channel.C_011,"(400, 600)"
368,2023-10-10_2_Channel.C_021,300,550,2.702228,0.006,2023-10-10,2,Channel.C_021,"(300, 550)"
370,2023-10-10_2_Channel.C_021,1550,1650,2.129132,0.039,2023-10-10,2,Channel.C_021,"(1550, 1650)"
400,2023-10-11_1_Channel.C_014,200,400,2.034085,0.045,2023-10-11,1,Channel.C_014,"(200, 400)"
449,2023-10-11_3_Channel.C_013,1650,1800,3.026091,0.002,2023-10-11,3,Channel.C_013,"(1650, 1800)"
479,2023-10-27_3_Channel.C_007,1750,1900,2.533262,0.015,2023-10-27,3,Channel.C_007,"(1750, 1900)"
481,2023-10-27_3_Channel.C_013,1600,1900,2.059445,0.043,2023-10-27,3,Channel.C_013,"(1600, 1900)"
512,2023-10-27_4_Channel.C_011,200,700,2.948020,0.013,2023-10-27,4,Channel.C_011,"(200, 700)"
518,2023-10-27_4_Channel.C_020,200,650,2.888715,0.010,2023-10-27,4,Channel.C_020,"(200, 650)"
527,2023-11-20_1_Channel.C_013,850,950,2.230932,0.038,2023-11-20,1,Channel.C_013,"(850, 950)"
540,2023-11-20_2_Channel.C_006,2200,2300,3.046154,0.008,2023-11-20,2,Channel.C_006,"(2200, 2300)"
638,2023-11-25_1_Channel.C_014,1500,1600,2.549832,0.014,2023-11-25,1,Channel.C_014,"(1500, 1600)"
642,2023-11-25_1_Channel.C_019,100,500,2.264352,0.028,2023-11-25,1,Channel.C_019,"(100, 500)"
676,2023-11-25_3_Channel.C_018,50,150,2.268348,0.038,2023-11-25,3,Channel.C_018,"(50, 150)"
724,2023-11-28_3_Channel.C_007,700,850,2.478462,0.019,2023-11-28,3,Channel.C_007,"(700, 850)"
745,2023-11-28_4_Channel.C_015,350,500,2.219731,0.039,2023-11-28,4,Channel.C_015,"(350, 500)"
771,2023-12-05_4_Channel.C_015,650,750,2.129610,0.043,2023-12-05,4,Channel.C_015,"(650, 750)"
791,2023-12-07_2_Channel.C_003,300,650,1.346868,0.047,2023-12-07,2,Channel.C_003,"(300, 650)"
802,2023-12-07_2_Channel.C_022,500,700,1.966875,0.035,2023-12-07,2,Channel.C_022,"(500, 700)"
865,2023-12-14_1_Channel.C_008,900,1050,2.170377,0.027,2023-12-14,1,Channel.C_008,"(900, 1050)"
873,2023-12-14_1_Channel.C_024,1450,1750,5.250529,0.000,2023-12-14,1,Channel.C_024,"(1450, 1750)"
904,2023-12-14_4_Channel.C_006,1900,2000,2.573589,0.013,2023-12-14,4,Channel.C_006,"(1900, 2000)"
907,2023-12-14_4_Channel.C_008,750,850,2.127436,0.035,2023-12-14,4,Channel.C_008,"(750, 850)"
917,2023-12-18_1_Channel.C_008_Unit 2,1900,2000,1.933099,0.034,2023-12-18,1,Channel.C_008_Unit 2,"(1900, 2000)"
931,2023-12-18_2_Channel.C_012_Unit 2,200,350,2.174497,0.030,2023-12-18,2,Channel.C_012_Unit 2,"(200, 350)"
945,2023-12-18_3_Channel.C_015_Unit 1,2000,2150,2.180261,0.036,2023-12-18,3,Channel.C_015_Unit 1,"(2000, 2150)"
946,2023-12-18_3_Channel.C_020_Unit 1,150,400,2.706683,0.008,2023-12-18,3,Channel.C_020_Unit 1,"(150, 400)"

In [ ]:
# Get spike counts anova passed windows
zom_spike_count_for_sig_windows_anova_passed = extract_spike_counts_from_windows(zom_sig_copy)

In [ ]:
zom_spike_count = zom_spike_count_for_sig_windows_anova_passed.copy()
zom_spike_count.head()

In [ ]:
zom_spike_count[['Date', 'Round No.', 'Cell']] = zom_spike_count['NeuronID'].str.split('_', n=2, expand=True)
zom_spike_count['Time Window'] = list(zip(zom_spike_count['WindowStart_ms'], zom_spike_count['WindowEnd_ms']))
zom_spike_count.head()

In [ ]:
zom_spike_count.head()
group_cols = ['Date', 'Round No.', 'Cell', 'Time Window', 'MonkeyName']
zom_spike_count['Date'] = zom_spike_count['Date'].astype(str)
zom_grouped_df = zom_spike_count.groupby(group_cols)['SpikeCount'].apply(list).reset_index()
zom_final_spike_count_df = zom_grouped_df.pivot(
    index=['Date', 'Round No.', 'Cell', 'Time Window'],
    columns='MonkeyName',
    values='SpikeCount'
).reset_index()
print(zom_final_spike_count_df.head())  # -- save this and share with Ed!!