# Multiple Regression

### Preparing predictors (X)

In [1]:
from analyses.enums.monkey_names import get_monkeys_by_default_order
from analyses.linear_regression.multiple_linear_regression import get_specific_behavioral_matrix
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# Get behavioral matrices (all are np arrays)
aff = get_specific_behavioral_matrix("affiliation")
sub = get_specific_behavioral_matrix("submission")
ago = get_specific_behavioral_matrix("agonism")

In [2]:
monkey_group = "Zombies"
monkeys = get_monkeys_by_default_order(monkey_group)

In [3]:
X = ago
X

array([[ 0,  4,  2,  7,  4,  7,  3,  9,  3,  2],
       [ 0,  0,  0,  2,  1,  1,  8,  4,  2,  0],
       [ 0,  1,  0,  0,  0,  7,  0,  1,  0,  2],
       [ 1,  8,  0,  0,  9,  5,  6, 10, 11,  2],
       [ 0,  0,  0,  0,  0,  1,  0,  1,  3, 10],
       [ 0,  0,  0,  0,  2,  0,  0,  0,  3,  1],
       [ 0,  0,  3,  2,  0,  4,  0,  1,  0,  6],
       [ 0,  1,  1,  0,  1,  0,  7,  0,  0,  1],
       [ 0,  0,  0,  2,  2,  5,  2,  3,  0,  6],
       [ 0,  0,  0,  0,  5,  4,  1,  0,  6,  0]])

In [ ]:
X_df = pd.DataFrame(X, index=monkeys, columns=[f'Feature{i+1}' for i in range(X.shape[1])])
X_df_clean = X_df.drop(index="81G")

### Preparing Y

In [12]:
from analyses.spike_rate import compute_mean_spike_rate_for_windows
subject_monkey_index = 6
sig_windows = pd.read_pickle(
        f'/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/{monkey_group}_significant_windows_pANOVAorGLM_passed.pkl')
ed_sig_windows = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/Ed and ANOVA/used_for_R01/R01_ed_list_duplicate_removed_without_full_window.pkl')
sig_windows = sig_windows[sig_windows['PermANOVA_p-value']<0.05]
mean_spike_rate_windows = compute_mean_spike_rate_for_windows(sig_windows)
sig_windows.shape

Computing windowed mean spike rate: 100%|██████████| 43/43 [00:00<00:00, 50.11it/s]

(43, 10)

In [5]:
spike_rate = mean_spike_rate_windows[mean_spike_rate_windows['MonkeyGroup']=='Zombies']
spike_rate = spike_rate[spike_rate['MonkeyName']!='NewMonkey']
# spike_rate = spike_rate[spike_rate['MonkeyName']!='7124']
spike_rate['MonkeyName'].unique()

array(['110E', '143H', '151J', '67G', '69X', '7124', '72X', '87J', '94B'],
      dtype=object)

## Run Multiple Regression 
Note that this would overfit due to the number of features (10) is larger than the number of monkeys (9). Plots for R-squared values not included since all R-squared values are 1. Also, p-values are all NaN. Use this result for gaining some directions on other multiple regression analysis. Do NOT conclude anything with the results

In [11]:
from analyses.linear_regression.multiple_linear_regression import run_simple_regression
results_df = run_simple_regression(spike_rate, X_df_clean)
results_df

Running OLS regressions: 100%|██████████| 43/43 [00:00<00:00, 1080.15it/s]

,NeuronWindowID,NeuronID,WindowStart_ms,WindowEnd_ms,R_squared,p_values,coefficients
0,"AMG_2023-09-26_3_Channel.C_027_Unit 2 (150.0, ...",AMG_2023-09-26_3_Channel.C_027_Unit 2,150.0,350.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[23.770521223203076, -1.0047250079107373, 1.13..."
1,"AMG_2023-10-03_1_Channel.C_009 (150.0, 600.0)",AMG_2023-10-03_1_Channel.C_009,150.0,600.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[25.722818462045716, -1.965119007715072, -0.97..."
2,"AMG_2023-10-03_3_Channel.C_006_Unit 1 (200.0, ...",AMG_2023-10-03_3_Channel.C_006_Unit 1,200.0,400.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[11.307250051865633, -0.5022770852008497, 1.89..."
3,"AMG_2023-10-03_3_Channel.C_006_Unit 1 (2150.0,...",AMG_2023-10-03_3_Channel.C_006_Unit 1,2150.0,2250.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[8.28695040402798, -0.5026939179018886, 1.7360..."
4,"AMG_2023-10-03_4_Channel.C_006 (450.0, 650.0)",AMG_2023-10-03_4_Channel.C_006,450.0,650.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[15.20503859131914, -0.4699390407597826, -0.30..."
5,"AMG_2023-10-04_1_Channel.C_004_Unit 1 (150.0, ...",AMG_2023-10-04_1_Channel.C_004_Unit 1,150.0,400.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[15.740172341460418, -0.4103140892452497, 2.67..."
6,"AMG_2023-10-04_1_Channel.C_019_Unit 3 (150.0, ...",AMG_2023-10-04_1_Channel.C_019_Unit 3,150.0,400.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[26.39134711408415, -0.41784609275538925, 3.45..."
7,"AMG_2023-10-04_2_Channel.C_018_Unit 1 (150.0, ...",AMG_2023-10-04_2_Channel.C_018_Unit 1,150.0,500.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[10.149341098478432, -0.25625276799425445, 2.1..."
8,"AMG_2023-10-04_3_Channel.C_002_Unit 1 (150.0, ...",AMG_2023-10-04_3_Channel.C_002_Unit 1,150.0,400.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[12.87157360832801, -0.4141578411047383, 1.625..."
9,"AMG_2023-10-04_3_Channel.C_004_Unit 2 (100.0, ...",AMG_2023-10-04_3_Channel.C_004_Unit 2,100.0,500.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[22.76091467888463, -0.734165754460678, 1.3686..."
10,"AMG_2023-10-04_3_Channel.C_009_Unit 1 (150.0, ...",AMG_2023-10-04_3_Channel.C_009_Unit 1,150.0,500.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[60.98066952419745, -1.5627024885484913, 7.379..."
11,"AMG_2023-10-04_3_Channel.C_009_Unit 3 (100.0, ...",AMG_2023-10-04_3_Channel.C_009_Unit 3,100.0,450.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[20.356889705007653, -0.7103517377993713, 0.40..."
12,"AMG_2023-10-04_4_Channel.C_021_Unit 2 (150.0, ...",AMG_2023-10-04_4_Channel.C_021_Unit 2,150.0,450.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[17.610453762219212, -0.4525986473830777, 0.13..."
13,"AMG_2023-10-04_4_Channel.C_022_Unit 2 (150.0, ...",AMG_2023-10-04_4_Channel.C_022_Unit 2,150.0,650.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[39.955166413926094, -0.5669872709841912, 5.21..."
14,"AMG_2023-10-04_4_Channel.C_027_Unit 1 (350.0, ...",AMG_2023-10-04_4_Channel.C_027_Unit 1,350.0,650.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[8.181972496879332, -0.02912185918817975, 0.74..."
15,"AMG_2023-10-05_2_Channel.C_009_Unit 1 (500.0, ...",AMG_2023-10-05_2_Channel.C_009_Unit 1,500.0,850.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[0.6808417345596851, 0.0156411768268161, -0.00..."
16,"AMG_2023-10-05_2_Channel.C_018_Unit 1 (50.0, 3...",AMG_2023-10-05_2_Channel.C_018_Unit 1,50.0,350.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[7.92446704031074, -0.12756908239783288, 0.027..."
17,"AMG_2023-10-09_3_Channel.C_013 (600.0, 750.0)",AMG_2023-10-09_3_Channel.C_013,600.0,750.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[0.45774158757723254, 0.04255236327321723, -0...."
18,"AMG_2023-10-10_2_Channel.C_007 (1150.0, 1250.0)",AMG_2023-10-10_2_Channel.C_007,1150.0,1250.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[15.808112019812869, -0.12251698102881282, 1.0..."
19,"AMG_2023-10-10_2_Channel.C_011 (400.0, 600.0)",AMG_2023-10-10_2_Channel.C_011,400.0,600.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[10.5431723258665, -0.10891855079796633, 2.197..."
20,"AMG_2023-10-10_2_Channel.C_021 (300.0, 550.0)",AMG_2023-10-10_2_Channel.C_021,300.0,550.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[9.05300295287492, -0.24454684189797446, 0.613..."
21,"AMG_2023-10-11_3_Channel.C_013 (1650.0, 1800.0)",AMG_2023-10-11_3_Channel.C_013,1650.0,1800.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[30.10100589997699, -0.1793045103090809, 1.779..."
22,"ER_2023-10-27_3_Channel.C_007 (1750.0, 1900.0)",ER_2023-10-27_3_Channel.C_007,1750.0,1900.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[2.2613946391536914, -0.10284456386569735, -0...."
23,"ER_2023-10-27_3_Channel.C_013 (1600.0, 1900.0)",ER_2023-10-27_3_Channel.C_013,1600.0,1900.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[20.665523784730645, -0.1938086596391066, 1.09..."
24,"ER_2023-10-27_4_Channel.C_011 (200.0, 700.0)",ER_2023-10-27_4_Channel.C_011,200.0,700.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[36.2026416082953, -1.1838556383650134, -0.770..."
25,"ER_2023-10-27_4_Channel.C_020 (200.0, 650.0)",ER_2023-10-27_4_Channel.C_020,200.0,650.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[34.69004460871249, -1.0162280715637977, -1.10..."
26,"ER_2023-11-25_1_Channel.C_014 (1500.0, 1600.0)",ER_2023-11-25_1_Channel.C_014,1500.0,1600.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[18.65712447781463, -0.25755674884821306, 1.26..."
27,"ER_2023-11-25_1_Channel.C_019 (100.0, 500.0)",ER_2023-11-25_1_Channel.C_019,100.0,500.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[2.9430487954480626, 0.0814365735670924, 0.564..."
28,"ER_2023-11-28_3_Channel.C_007 (700.0, 850.0)",ER_2023-11-28_3_Channel.C_007,700.0,850.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[23.071120265754793, -0.2947044006828228, 1.93..."
29,"ER_2023-11-28_4_Channel.C_015 (350.0, 500.0)",ER_2023-11-28_4_Channel.C_015,350.0,500.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[15.808039452022806, -0.5009068685058622, 2.50..."
30,"ER_2023-12-05_4_Channel.C_015 (650.0, 750.0)",ER_2023-12-05_4_Channel.C_015,650.0,750.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[11.060869390052579, 0.06876769784669555, 1.41..."
31,"ER_2023-12-07_2_Channel.C_022 (500.0, 700.0)",ER_2023-12-07_2_Channel.C_022,500.0,700.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[6.1486885577640304, -0.08440039028490431, 0.6..."
32,"ER_2023-12-14_1_Channel.C_008 (900.0, 1050.0)",ER_2023-12-14_1_Channel.C_008,900.0,1050.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[38.477156839936676, -0.48467499157235644, 0.1..."
33,"ER_2023-12-14_1_Channel.C_024 (1450.0, 1750.0)",ER_2023-12-14_1_Channel.C_024,1450.0,1750.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[6.313595541124511, -0.13660056293254833, 1.73..."
34,"ER_2023-12-14_4_Channel.C_006 (1900.0, 2000.0)",ER_2023-12-14_4_Channel.C_006,1900.0,2000.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[8.62773802890353, -0.19249418429425516, -0.32..."
35,"ER_2023-12-14_4_Channel.C_008 (750.0, 850.0)",ER_2023-12-14_4_Channel.C_008,750.0,850.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[4.703922389072371, -0.21012398701910528, 0.58..."
36,"ER_2023-12-18_3_Channel.C_015_Unit 1 (2000.0, ...",ER_2023-12-18_3_Channel.C_015_Unit 1,2000.0,2150.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[9.273335485621248, -0.031916899109225357, 0.4..."
37,"Unknown_2023-10-31_1_Channel.C_005 (200.0, 500.0)",Unknown_2023-10-31_1_Channel.C_005,200.0,500.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[6.815572038520048, -0.32911712188965464, 0.62..."
38,"Unknown_2023-10-31_1_Channel.C_020 (200.0, 500.0)",Unknown_2023-10-31_1_Channel.C_020,200.0,500.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[9.795063293424489, -0.41959131097225855, 0.50..."
39,"Unknown_2023-10-31_1_Channel.C_021 (2550.0, 27...",Unknown_2023-10-31_1_Channel.C_021,2550.0,2700.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[6.556834371938605, -0.20781134568916074, 1.67..."
40,"Unknown_2023-11-08_1_Channel.C_005 (1100.0, 12...",Unknown_2023-11-08_1_Channel.C_005,1100.0,1200.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[-0.16531179469744062, -0.07182790168735369, -..."
41,"Unknown_2023-11-08_1_Channel.C_007 (150.0, 450.0)",Unknown_2023-11-08_1_Channel.C_007,150.0,450.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[8.622768238812295, -0.32214451736586736, 0.92..."
42,"Unknown_2023-11-08_2_Channel.C_015 (350.0, 500.0)",Unknown_2023-11-08_2_Channel.C_015,350.0,500.0,1.0,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[21.573457477740387, -0.3725293027858688, 1.40..."

In [ ]:
# import matplotlib.pyplot as plt
# %matplotlib inline
# plt.figure(figsize=(6, 4))
# plt.hist(results_df['R_squared'], bins=30, color='gray', edgecolor='black')
# plt.xlabel('R-squared')
# plt.ylabel('Number of Windows')
# plt.title('Distribution of R² across Neuron × Window')
# plt.grid(True)
# plt.tight_layout()
# plt.show()

In [ ]:
# threshold = 0.6
# n_sig = (results_df['R_squared'] > threshold).sum()
# n_total = len(results_df)
# 
# print(f"{n_sig} out of {n_total} windows had R² > {threshold:.2f} ({n_sig / n_total:.1%})")

In [13]:
# import pandas as pd
# import matplotlib.pyplot as plt
# 
# # Convert list of coefficients into a DataFrame
# coeff_df = pd.DataFrame(results_df['coefficients'].tolist(),
#                         index=results_df.index)
# 
# # Plotting all coefficient vectors as lines
# plt.figure(figsize=(10, 6))
# for i, row in coeff_df.iterrows():
#     plt.plot(row.values, alpha=0.5, label=f'{results_df.iloc[i]["NeuronID"]}' if i < 10 else "")  # label only first few
# plt.xlabel("Predictor Index")
# plt.ylabel("Coefficient Value")
# plt.title("Regression Coefficients Across Neurons")
# plt.grid(True)
# plt.axhline(0, color='black', linestyle='--')
# plt.tight_layout()
# plt.legend(loc="best", fontsize=8)
# plt.show()

In [14]:
results_df[['NeuronWindowID','coefficients']]

,NeuronWindowID,coefficients
0,"AMG_2023-09-26_3_Channel.C_027_Unit 2 (150.0, ...","[23.770521223203076, -1.0047250079107373, 1.13..."
1,"AMG_2023-10-03_1_Channel.C_009 (150.0, 600.0)","[25.722818462045716, -1.965119007715072, -0.97..."
2,"AMG_2023-10-03_3_Channel.C_006_Unit 1 (200.0, ...","[11.307250051865633, -0.5022770852008497, 1.89..."
3,"AMG_2023-10-03_3_Channel.C_006_Unit 1 (2150.0,...","[8.28695040402798, -0.5026939179018886, 1.7360..."
4,"AMG_2023-10-03_4_Channel.C_006 (450.0, 650.0)","[15.20503859131914, -0.4699390407597826, -0.30..."
5,"AMG_2023-10-04_1_Channel.C_004_Unit 1 (150.0, ...","[15.740172341460418, -0.4103140892452497, 2.67..."
6,"AMG_2023-10-04_1_Channel.C_019_Unit 3 (150.0, ...","[26.39134711408415, -0.41784609275538925, 3.45..."
7,"AMG_2023-10-04_2_Channel.C_018_Unit 1 (150.0, ...","[10.149341098478432, -0.25625276799425445, 2.1..."
8,"AMG_2023-10-04_3_Channel.C_002_Unit 1 (150.0, ...","[12.87157360832801, -0.4141578411047383, 1.625..."
9,"AMG_2023-10-04_3_Channel.C_004_Unit 2 (100.0, ...","[22.76091467888463, -0.734165754460678, 1.3686..."
10,"AMG_2023-10-04_3_Channel.C_009_Unit 1 (150.0, ...","[60.98066952419745, -1.5627024885484913, 7.379..."
11,"AMG_2023-10-04_3_Channel.C_009_Unit 3 (100.0, ...","[20.356889705007653, -0.7103517377993713, 0.40..."
12,"AMG_2023-10-04_4_Channel.C_021_Unit 2 (150.0, ...","[17.610453762219212, -0.4525986473830777, 0.13..."
13,"AMG_2023-10-04_4_Channel.C_022_Unit 2 (150.0, ...","[39.955166413926094, -0.5669872709841912, 5.21..."
14,"AMG_2023-10-04_4_Channel.C_027_Unit 1 (350.0, ...","[8.181972496879332, -0.02912185918817975, 0.74..."
15,"AMG_2023-10-05_2_Channel.C_009_Unit 1 (500.0, ...","[0.6808417345596851, 0.0156411768268161, -0.00..."
16,"AMG_2023-10-05_2_Channel.C_018_Unit 1 (50.0, 3...","[7.92446704031074, -0.12756908239783288, 0.027..."
17,"AMG_2023-10-09_3_Channel.C_013 (600.0, 750.0)","[0.45774158757723254, 0.04255236327321723, -0...."
18,"AMG_2023-10-10_2_Channel.C_007 (1150.0, 1250.0)","[15.808112019812869, -0.12251698102881282, 1.0..."
19,"AMG_2023-10-10_2_Channel.C_011 (400.0, 600.0)","[10.5431723258665, -0.10891855079796633, 2.197..."
20,"AMG_2023-10-10_2_Channel.C_021 (300.0, 550.0)","[9.05300295287492, -0.24454684189797446, 0.613..."
21,"AMG_2023-10-11_3_Channel.C_013 (1650.0, 1800.0)","[30.10100589997699, -0.1793045103090809, 1.779..."
22,"ER_2023-10-27_3_Channel.C_007 (1750.0, 1900.0)","[2.2613946391536914, -0.10284456386569735, -0...."
23,"ER_2023-10-27_3_Channel.C_013 (1600.0, 1900.0)","[20.665523784730645, -0.1938086596391066, 1.09..."
24,"ER_2023-10-27_4_Channel.C_011 (200.0, 700.0)","[36.2026416082953, -1.1838556383650134, -0.770..."
25,"ER_2023-10-27_4_Channel.C_020 (200.0, 650.0)","[34.69004460871249, -1.0162280715637977, -1.10..."
26,"ER_2023-11-25_1_Channel.C_014 (1500.0, 1600.0)","[18.65712447781463, -0.25755674884821306, 1.26..."
27,"ER_2023-11-25_1_Channel.C_019 (100.0, 500.0)","[2.9430487954480626, 0.0814365735670924, 0.564..."
28,"ER_2023-11-28_3_Channel.C_007 (700.0, 850.0)","[23.071120265754793, -0.2947044006828228, 1.93..."
29,"ER_2023-11-28_4_Channel.C_015 (350.0, 500.0)","[15.808039452022806, -0.5009068685058622, 2.50..."
30,"ER_2023-12-05_4_Channel.C_015 (650.0, 750.0)","[11.060869390052579, 0.06876769784669555, 1.41..."
31,"ER_2023-12-07_2_Channel.C_022 (500.0, 700.0)","[6.1486885577640304, -0.08440039028490431, 0.6..."
32,"ER_2023-12-14_1_Channel.C_008 (900.0, 1050.0)","[38.477156839936676, -0.48467499157235644, 0.1..."
33,"ER_2023-12-14_1_Channel.C_024 (1450.0, 1750.0)","[6.313595541124511, -0.13660056293254833, 1.73..."
34,"ER_2023-12-14_4_Channel.C_006 (1900.0, 2000.0)","[8.62773802890353, -0.19249418429425516, -0.32..."
35,"ER_2023-12-14_4_Channel.C_008 (750.0, 850.0)","[4.703922389072371, -0.21012398701910528, 0.58..."
36,"ER_2023-12-18_3_Channel.C_015_Unit 1 (2000.0, ...","[9.273335485621248, -0.031916899109225357, 0.4..."
37,"Unknown_2023-10-31_1_Channel.C_005 (200.0, 500.0)","[6.815572038520048, -0.32911712188965464, 0.62..."
38,"Unknown_2023-10-31_1_Channel.C_020 (200.0, 500.0)","[9.795063293424489, -0.41959131097225855, 0.50..."
39,"Unknown_2023-10-31_1_Channel.C_021 (2550.0, 27...","[6.556834371938605, -0.20781134568916074, 1.67..."
40,"Unknown_2023-11-08_1_Channel.C_005 (1100.0, 12...","[-0.16531179469744062, -0.07182790168735369, -..."
41,"Unknown_2023-11-08_1_Channel.C_007 (150.0, 450.0)","[8.622768238812295, -0.32214451736586736, 0.92..."
42,"Unknown_2023-11-08_2_Channel.C_015 (350.0, 500.0)","[21.573457477740387, -0.3725293027858688, 1.40..."

In [15]:
# Extract the coefficients column as a new DataFrame
coeff_df = pd.DataFrame(results_df['coefficients'].tolist(),
                        index=results_df['NeuronWindowID']) 

filtered_monkey_list = [m for m in monkeys if m not in ["81G"]]
coeff_df.columns = ['intercepts'] + monkeys

plt.figure(figsize=(12, 10))
# ax = sns.heatmap(coeff_df, cmap='coolwarm', center=0, annot=True, fmt=".1f",
#                  yticklabels=True, cbar=True)
ax = sns.heatmap(coeff_df.iloc[:, 1:], cmap='coolwarm', center=0, annot=True, fmt=".1f",
                 yticklabels=True, cbar=True) # intercept removed


# Adjust label fonts AFTER the heatmap has rendered
ax.set_yticklabels(ax.get_yticklabels(), fontsize=7, rotation=0)

# Fix for misalignment: force re-draw with tight layout
plt.tight_layout()
plt.title("Heatmap of Regression Coefficients per Neuron", fontsize=14)
plt.xlabel("Agonism From")
plt.ylabel("Neuron ID")
plt.show()